# Generated by Django 3.1.2 on 2023-06-08 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAndroidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^01[013456789][\\d]{8}$', 'Invalid mobile number.')])),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('fcm_token', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'registered_android_users',
            },
        ),
    ]
