# Generated by Django 3.1.2 on 2023-06-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_user_count', models.PositiveIntegerField()),
                ('success_count', models.PositiveIntegerField()),
                ('fail_count', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notification_records',
            },
        ),
    ]
