# Generated by Django 4.2 on 2023-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics/clubs')),
                ('desc', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('is_club_in_city', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics/players/')),
                ('desc', models.TextField()),
                ('country', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
